Library/Books/urls.py
from django.contrib import admin
from django.urls import path
from Books import views
app_name='Books'
urlpatterns = [

    path('',views.home,name="home"),           #http:127.0.0.1:8000
    path('addbook',views.addbook,name="addbook"),
    path('addbook1',views.addbook1,name="addbook1"),#http:127.0.0.1:8000/addbook
    path('viewbook',views.viewbook,name="viewbook"),#http:127.0.0.1:8000/viewbook
    path('bookdetail/<int:i>',views.bookdetail,name="bookdetail"),
    path('editbook',views.editbook,name="editbook"),

]

Library/Library/urls.py
from django.contrib import admin
from django.urls import path,include
from Books import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Books.urls')),
    path('addbook',views.addbook,name='addbook'),
    path('users/', include('Users.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Library/Users/urls.py
from django.contrib import admin
from django.urls import path
from Users import views
app_name='Users'
urlpatterns = [

    path('',views.register,name="register"),           #http:127.0.0.1:8000
    path('login',views.login,name="login"),                   #http:127.0.0.1:8000/addbook
    path('logout',views.logout,name="logout"),       #http:127.0.0.1:8000/viewbook

]

Library/Books/models.py
from django.db import models

# Create your models here.
#Model definition (database schema)
class Books(models.Model):
    Title=models.CharField(max_length=100)
    Author=models.CharField(max_length=50)
    Price=models.IntegerField()
    Pages=models.IntegerField()
    Language=models.CharField(max_length=10)
    Image=models.ImageField(upload_to="Books")

#

Library/Users/models.py
from django.db import models

# Create your models here.

Library/Books/forms.py
from django import forms
# class addbookForm(forms.Form):
#     Title=forms.CharField()
#     Author=forms.CharField()
#     Price=forms.IntegerField()
#     Pages=forms.IntegerField()
#     Language_choices=[('english','English'),('french','French'),('malayalam','Malayalam'),('hindi','Hindi')]
#     Language = forms.ChoiceField(choices=Language_choices)
#     Image=forms.ImageField()

# using ModelForm
from Books.models import Books
class addbookForm(forms.ModelForm):
    class Meta:  #inner class used to give description about form structure
        model=Books
        #fields="_all_"
        #or
        fields=['Title','Author','Price','Language','Pages','Image']

Library/Books/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect

# Create your views here.
def home(request):
    return render(request,'home.html')

# def addbook(request):
#     return render(request,'addbook.html')
# ##user defined
from Books.models  import Books
def addbook1(request):
    if (request.method == "POST"):  ##after form submission
        print(request.POST)
        print(request.FILES)
        t=request.POST['t']
        a = request.POST['a']
        p = request.POST['p']
        pg= request.POST['pg']
        l = request.POST['l']
        i=request.FILES['i']
        b=Books.objects.create(Title=t,Author=a,Price=p,Pages=pg,Language=l,Image=i)
        b.save()
        return render(request, 'addbook1.html')
    return render(request,'addbook1.html')


def viewbook(request):
    b = Book.objects.all()
    print(b)
    return render(request,'viewbook.html',{'Books':b})


##built in

from Books.forms import addbookForm
def addbook(request):
    if (request.method == "POST"):
        ##after form submission
        # print(request.POST)
        # print(request.FILES)
        form_instance=addbookForm(request.POST,request.FILES)
        if form_instance.is_valid():
        #     # data=form_instance.cleaned_data
            # t = request.POST['t']
            # a = request.POST['a']
            # p = request.POST['p']
            # pg = request.POST['pg']
            # l = request.POST['l']
            # b = Books.objects.create(Title=t, Author=a, Price=p, Pages=pg, Language=l)
            # b=Books.objects.create(Title=form_instance.cleaned_data['Title'],
            #                         Author =form_instance.cleaned_data['Author'],
            #                        Price=form_instance.cleaned_data['Price'],
            #                        Pages=form_instance.cleaned_data['Pages'],
            #                        Language=form_instance.cleaned_data['Language'],
            #                        Image=form_instance.cleaned_data['Image'])
            #
            # b.save()
            form_instance.save()
            #redirect(pathname)
        return redirect('Books:home')

    form_instance = addbookForm()
    return render(request, 'addbook.html', {'form': form_instance})


#detail view
def bookdetail(request,i):
    print(i)
    b=Book.objects.get(id=i)
    return render(request,'detail.html',{'Books':b})

#Edit view
def editbook(request):
    return render(request,'editbook.html')

Library/Users/views.py
from django.shortcuts import render

# Create your views here.
def register(request):
    return render(request,'register.html')

def login(request):
    return render(request,'login.html')

def logout(request):
    return render(request,'logout.html')

Library/templates/addbook.html
{%  extends 'base.html'   %}
{% load crispy_forms_tags %}
{% block title %}
    <title> Add </title>
     {% endblock %}
{% block content %}
<center><h1>ADD BOOK(built in)</h1></center>
<div class="container w-50 border border-2 px-5 pb-5 pt-5 mt-5">
<form method="post" enctype="multipart/form-data">
     {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" >

</form>
</div>
{% endblock %}

Library/templates/addbook1.html
{%  extends 'base.html'   %}
{% load crispy_forms_tags %}
{% block title %}
    <title> Add </title>
     {% endblock %}
{% block content %}
<center><h1>ADD BOOK(user defined)</h1></center>
<div class="container w-50 border border-2 px-5 pb-5 pt-5 mt-5">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
     <div class="mb-3">
         <label class="from-label">Title</label>
         <input type="text" name="t" class="form-control">
     </div>
    <div class="mb-3">
         <label class="from-label">Author</label>
         <input type="text" name="a" class="form-control">
     </div>
    <div class="mb-3">
         <label class="from-label">Price</label>
         <input type="number" name="p" class="form-control">
     </div>
    <div class="mb-3">
         <label class="from-label">Pages</label>
         <input type="number" name="pg" class="form-control">
     </div>
    <div class="mb-3">
         <label class="from-label">Language</label>
         <input type="text" name="l" class="form-control">
     </div>
    <div class="mb-3">
         <label class="from-label">Image</label>
         <input type="file" name="i" class="form-control">
     </div>
    <input type="submit" >

</form>
</div>
{% endblock %}

Library/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
  {% block title %}
  {% endblock %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<!--    always paste bootstrap link abovecustom link-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'Books:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Books:addbook' %}">AddBook</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Books:addbook1' %}">AddBook1</a>
        </li>

        <li class="nav-item">
          <a class="nav-link " href="{% url 'Books:viewbook' %}">ViewBook</a>
        </li>
         <li class="nav-item">
          <a class="nav-link " href="{% url 'Users:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'Users:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'Users:logout' %}">Logout</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% block content %}
hello
{% endblock %}

</body>
</html>

Library/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Library/templates/editbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit </title>
</head>
<body>

</body>
</html>

Library/templates/home.html
{% extends 'base.html' %}
{% block title %}
<title>Home</title>
{% endblock %}
{% block content %}
<h2>WELCOME TO HOMEPAGE</h2>
{% endblock %}

Library/templates/login.html
{% extends 'base.html' %}
{% block title %}
<title>Login Page</title>
{% endblock %}
{% block content %}
<h2>LOGIN</h2>
{% endblock %}

Library/templates/logout.html
{% extends 'base.html' %}
{% block title %}
<title>Logout Page</title>
{% endblock %}
{% block content %}
<h2>LOGOUT</h2>
{% endblock %}

Library/templates/register.html
{% extends 'base.html' %}
{% block title %}
<title>Register</title>
{% endblock %}
{% block content %}
<h2>REGISTER</h2>
{% endblock %}

Library/templates/viewbook.html
{% extends 'base.html'%}
    {% block title %}
    <title>viewbook</title>
    {% endblock %}
{% block content %}
<h2>View Book</h2>
<!--{{ books }}-->
<div class="container w-75 mt-3 p-5">
<table class="table table-bordered">
    <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Price</th>
        <th>Pages</th>
        <th>Language</th>
        <th>Cover</th>
        <th>Actions</th>
    </tr>
    {% for b in books %}
    <tr>
        <td>{{b.Title}}</td>
        <td>{{b.Author}}</td>
        <td>{{b.Price}}</td>
        <td>{{b.Pages}}</td>
        <td>{{b.Language}}</td>
        <td><img src="{{b.image.url}}" height="150px" width="150px"></td>
        <td><a class="btn btn-light me-4" href="{% url 'books:bookdetail' b.id %}">Detail</a>
            <a class="btn btn-light me-4" href="{% url 'books:editbook' %}">Edit</a>
            <a class="btn btn-light me-4">Delete</a>
        </td>
    </tr>
    {% endfor %}
</table>
    </div>
{% endblock %}