LibraryClass/books/urls.py
from django.contrib import admin
from django.urls import path
from books import views
from django.conf.urls.static import static
from django.conf import settings



app_name='books'
urlpatterns = [

    # path('',views.home,name="home"),           #http:127.0.0.1:8000
    path('',views.HomeView.as_view(),name="home"),
    # path('addbook',views.addbook,name="addbook"),
    path('addbook',views.AddBookView.as_view(),name="addbook"),
    # path('addbook1', views.addbook1, name="addbook1"),#http:127.0.0.1:8000/addbook
    path('addbook1',views.AddBook1View.as_view(),name="addbook1"),
    # path('viewbook',views.viewbook,name="viewbook"),  #http:127.0.0.1:8000/viewbook
    path('viewbook',views.ViewBookView.as_view(),name="viewbook"),
    # path('bookdetail/<int:i>', views.bookdetail, name="bookdetail"),
    path('bookdetail/<int:i>', views.BookDetailView.as_view(), name="bookdetail"),
    # path('deletebook/<int:i>', views.deletebook, name="deletebook"),
    path('deletebook/<int:i>', views.DeleteBookView.as_view(), name="deletebook"),
    # path('editbook/<int:i>', views.editbook, name="editbook"),
    path('editbook/<int:i>', views.EditBookView.as_view(), name="editbook"),
    # path('searchbook', views.searchbook, name="searchbook"),
    path('searchbook', views.SearchBookView.as_view(), name="searchbook"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

LibraryClass/library/urls.py
from django.contrib import admin
from django.urls import path,include
from  books  import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

LibraryClass/users/urls.py
from django.contrib import admin
from django.urls import path
from users import views
app_name='users'

urlpatterns = [
    path('',views.register,name="register"),           #http:127.0.0.1:8000
    path('login',views.login,name="login"),                   #http:127.0.0.1:8000/addbook
    path('logout',views.logout,name="logout"),       #http:127.0.0.1:8000/viewbook

]

LibraryClass/templates/addbook.html
{%  extends 'base.html'   %}
{% load crispy_forms_tags %}
{% block title %}
    <title> Add </title>
     {% endblock %}
{% block content %}
<center><h1>ADD BOOK(built in form)</h1></center>
<div class="container w-50 border border-2 px-5 pb-5 pt-5 mt-5">
<form method="post" enctype="multipart/form-data">
     {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" >

</form>
</div>
{% endblock %}

LibraryClass/templates/addbook1.html
{% extends 'base.html' %}
{% block title %}
    <title>Home</title>
    {% endblock  %}
{% block content %}
<h1><center>ADD BOOK 1(user defined) </center></h1>

<div class="container w-50 border border-2 px-5 pb-5 pt-5 mt-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
     <div class="mb-3">
         <label class="from-label">Title</label>
         <input type="text"  name="t" class="form-control">
     </div>
    <div class="mb-3">
         <label class="from-label">Author</label>
         <input type="text" name="a" class="form-control">
     </div>
    <div class="mb-3">
         <label class="from-label">Price</label>
         <input type="number" name="p" class="form-control">
     </div>
    <div class="mb-3">
         <label class="from-label">Pages</label>
         <input type="number" name="g" class="form-control">
     </div>
    <div class="mb-3">
         <label class="from-label">Language</label>
         <input type="text" name="l"  class="form-control">
     </div>
        <div class="mb-3">
            <label class="from-label">Image</label>
            <input type="file" name="i"  class="form-control">
        </div>
    <input type="submit" >

</form>
</div>
{% endblock %}

LibraryClass/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
  {% block title %}
  {% endblock %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<!--    always paste bootstrap link abovecustom link-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'books:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:addbook' %}">AddBook</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:addbook1' %}">AddBook1</a>
        </li>


        <li class="nav-item">
          <a class="nav-link " href="{% url 'books:viewbook' %}">ViewBook</a>
        </li>
         <li class="nav-item">
          <a class="nav-link " href="{% url 'users:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'users:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'users:logout' %}">Logout</a>
        </li>
      </ul>
      <form class="d-flex" method="POST" action="{% url 'books:searchbook' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="text" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% block content %}
hello
{% endblock %}

</body>
</html>

LibraryClass/templates/detail.html
{% extends 'base.html'%}
    {% block title %}
<title>Book Detail</title>
    {% endblock %}
{% block content %}
<div class="container w-50 mx-auto mt-4">

<h2>Book Detail</h2>
<table class ="table table-bordered mt-4 text-centered">
    <tr>
        <th>Title</th>
        <td>{{ books.Title}}</td>
    </tr>
    <tr>
        <th>Author</th>
        <td>{{ books.Author}}</td>
    </tr>
    <tr>
        <th>Price</th>
        <td>{{ books.Price}}</td>
    </tr>
    <tr>
        <th>Pages</th>
        <td>{{ books.Pages}}</td>
    </tr>
    <tr>
        <th>Language</th>
        <td>{{ books.Language}}</td>
    </tr>
    <tr>
        <th>Cover</th>
        <td><img src = "{{ books.Image.url}}"height="150px" width="150px"></td>
    </tr>
</table>
</div>


{% endblock %}

LibraryClass/templates/editbook.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
    {% block title %}
    <title>Edit Book</title>
    {% endblock %}
{% block content %}
<h2>Edit Book</h2>
<div class="container w-50 border border-2 px-5 pb-5 pt-5 mt-5">
<form method="post" enctype="multipart/form-data">
     {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" >

</form>
</div>
{% endblock %}

LibraryClass/templates/home.html
{% extends 'base.html' %}
{% block title %}
    <title>Home</title>
    {% endblock  %}
{% block content %}
<h1><center>WELCOME TO HOME PAGE</center></h1>
{% endblock %}


<!--<a href="{% url 'books:home' %}">Home</a>-->
<!--<a href="{% url 'books:addbook' %}">AddBook</a>-->
<!--<a href="{% url 'books:viewbook' %}">ViewBook</a>-->
<!--<a href="{% url 'users:register' %}">Register</a>-->
<!--<a href="{% url 'users:login' %}">Login</a>-->
<!--<a href="{% url 'users:logout' %}">Logout</a>-->

LibraryClass/templates/login.html
{% extends 'base.html' %}
{% block title %}
    <title>login</title>
    {% endblock  %}
{% block content %}
<h1><center>LOGIN PAGE</center></h1>
{% endblock %}

LibraryClass/templates/logout.html
{% extends 'base.html' %}
{% block title %}
    <title>logout</title>
    {% endblock  %}
{% block content %}
<h1><center>LOGOUT PAGE</center></h1>
{% endblock %}

LibraryClass/templates/register.html
{% extends 'base.html' %}
{% block title %}
    <title>register</title>
    {% endblock  %}
{% block content %}
<h1><center>REGISTER</center></h1>
{% endblock %}

LibraryClass/templates/searchbook.html
{% extends 'base.html' %}
{% block title %}
    <title>Searchbook</title>
    {% endblock  %}
{% block content %}
<div class="container w-75 mt-3 p-5">
    <h2>Search Books</h2>
{% if books %}
    <table class ="table table-bordered text-centered">
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Price</th>
            <th>Languages</th>
            <th>Pages</th>
            <th>Cover</th>

        </tr>
        {% for b in books %}
        <tr>
            <td>{{ b.Title }}</td>
            <td>{{ b.Author }}</td>
            <td>{{ b.Price }}</td>
            <td>{{ b.Language }}</td>
            <td>{{ b.Pages }}</td>
            <td><img src="{{ b.Image.url}}"height="150px" width="150px"></td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
<h2>No Search Results</h2>
    {% endif %}
</div>
{% endblock %}

LibraryClass/templates/viewbook.html
{% extends 'base.html' %}
{% block title %}
    <title>viewbook</title>
    {% endblock  %}
{% block content %}
<h1><center>BOOK LIST</center></h1>
{{books}}       <!-- all  data from books-->
<div class="container w-75 mt-3 p-5">
    <table class ="table table-bordered">
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Price</th>
            <th>Languages</th>
            <th>Pages</th>
            <th>Cover</th>
            <th>Actions</th>
        </tr>
        {% for b in books %}
        <tr>
            <td>{{ b.Title }}</td>
            <td>{{ b.Author }}</td>
            <td>{{ b.Price }}</td>
            <td>{{ b.Language }}</td>
            <td>{{ b.Pages }}</td>
            <td><img src="{{ b.Image.url}}"height="150px" width="150px"></td>
            <td><a class="btn btn-light me-4" href="{% url 'books:bookdetail' b.id %}">Detail</a>
                <a class="btn btn-light me-4" href="{% url 'books:editbook' b.id%}">Edit</a>
                <a class="btn btn-light me-4" href="{% url 'books:deletebook' b.id %}">Delete</a></td>

        </tr>
        {% endfor %}
    </table>
    <!--<ol>-->
        <!--{% for b in books %}-->
        <!--<li>Book Details</li>-->
        <!--<ul>-->
        <!--<li>Title-{{ b.Title }}</li>-->
        <!--<li>Author-{{ b.Author }}</li>-->
        <!--<li>Price-{{ b.Price }}</li>-->
        <!--<li>Language-{{ b.Language }}</li>-->
        <!--<li>Pages-{{ b.Pages }}</li>-->
        <!--</ul>-->
        <!--{% endfor %}-->
    <!--</ol>-->

</div>

<!--{% for b in books %}-->
    <!--<p>{{ b.Title }}</p>-->
    <!--<p>{{ b.Author }}</p>-->
    <!--<p>{{ b.Pages }}</p>-->
    <!--<p>{{ b.Price }}</p>-->
    <!--<p>{{ b.Language }}</p>-->
    <!--<p>{{ b.Image }}</p>-->
<!--<hr>-->
{% endfor %}
{% endblock %}